### ISSUE TITLE
How to generate training pkls and theme files from POP909

### ISSUE THREAD

**Issue by 2000222** [atosystem/ThemeTransformer#1]
Hello, your work is so brilliant and I've completed the inference process for some provided theme files (e.g., 875_theme.mid). 
But I feel a little confused how to generate the similar theme file from POP909 and how to obtain the training pkl files (train_seg2_512.pkl & val_seg2_512.pkl) from scratch. 
If possible, could you pls share some related ideas or scripts? Thank you~~

**Comment by atosystem** [comment]
Dear @2000222 

So sorry for the late reply...

Thanks for trying out Theme Transformer!

I have to apologize for the absence of the Theme retrieval code. 

## For Theme midi file

Although the theme retrieval code is not available in this repo, you can still create your own Theme MIDI files by following the  following format (which is seen in`./theme_files/` ) 

(which contains 3 tracks: naming “MELODY”, “PIANO” and “Theme info track”)

For example, the following is the screenshot of `./theme_files/874_theme.mid`


![image](https://user-images.githubusercontent.com/32225867/147510605-ab6b9c85-ff56-46e3-89e5-9bc876c18030.png)

As for the length of the theme (number of bars), we use the length of 2 bars in our work, but the model should work without error with longer themes.

However, we do not guarantee the quality of the themes beyond POP909 dataset or themes longer than 2 bars, as our model is trained on 2-bar segment themes in POP909.

You can inference music by our model with your custom theme MIDI files.

## For .pkl files

The pkl files contain REMI sequences for training and testing of our model. They are attained by gathering a bunch of remi sequences from annotated individual midi files.

For midi annotations:
![image](https://user-images.githubusercontent.com/32225867/147511432-6992f921-f44b-41f1-82b4-8a2c91463e67.png)
Each midi file must contain 5 tracks. (The first 3 tracks directly come from POP909 only preprocessed with 1/16 bar quantize)

others:
* `boundary_track` : indicates the boundary of each music segment. (We employ 2-bar segmentation in our paper. You are welcome to use other phrase segmentation methods). The onset and offset of the notes correspond to the start and the end of the music segment. The pitch has no physical meaning, but please use the same value for every segment.

* `melody_boundary_track` (Optional, you can leave it blank): indicates the cluster for each music segment. The segments with same pitch are in the same cluster (they sound similar). Notice that the lowest pitch for the notes in this track must be the pitch in `boundary_track`

*  `theme info track` : indicates the music segments that are selected as **theme**

> Because we do not provide the theme retrieval code currently, you must decide the theme region by yourself, as well as boundaries.


| `boundary_track` | `melody_boundary_track` | `theme info track` |
| -------- | -------- | -------- |
| ![image](https://user-images.githubusercontent.com/32225867/147512228-973c6284-298a-444e-889e-0ead13c52ee9.png)    | ![image](https://user-images.githubusercontent.com/32225867/147512235-d9d1b8cd-ed3c-43c1-a7ed-5b045494e46a.png)     | ![image](https://user-images.githubusercontent.com/32225867/147512256-f186d26f-f235-40b8-b4d4-3c5eca166187.png)     |

After the annotations are done, please call the following 2 functions

* midi2REMI : converting midifile to REMI sequence
https://github.com/atosystem/ThemeTransformer/blob/5ad990d259d6211f62cfb307135601c8e0e35773/preprocess/vocab.py#L158-L173

* preprocessREMI : preprocess REMI sequence for model input
https://github.com/atosystem/ThemeTransformer/blob/5ad990d259d6211f62cfb307135601c8e0e35773/preprocess/vocab.py#L360-L378

Example:
For each midi:
```python
remi_seq = myvocab.midi2REMI(midifp,include_bridge=False,bar_first=False,verbose=False)
ret = myvocab.preprocessREMI(remi_seq,always_include=True,max_seq_len=512,verbose=True)
```
Finally, you can collect all `ret` for each song and insert them into a list and save it to pkl.

Again, Thanks a lot  for using Theme Transformer~

**Comment by 2000222** [comment]
Thanks a lot for your tutorial. 💛  Exactly, I've created a manual theme_file with three tracks inspired by my favorite singer and applied the ThemeTransformer to generate new music. 
😄 Hope a good publication and presentation for your brilliant work ~

**Comment by asummerdayjxf** [comment]
Hello, I am a beginner in music generation, I still don't understand the code, I want to know what to enter in the interface after python train.py?
