### ISSUE TITLE
Install requirements fails

### ISSUE THREAD

**Issue by afrozas** [atosystem/ThemeTransformer#4]
Running `pip install -r requirements.txt` from root fails with
```
Collecting cycler==0.10.0
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
ERROR: Could not find a version that satisfies the requirement dataclasses==0.8 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.8
```

Is the version pinning required for training the model? If not, using `>=` would be better.

Thanks!

**Comment by atosystem** [comment]
@afrozas Thanks for point out !

**Comment by atosystem** [comment]
@afrozas  Thanks for pointing it out!
It turns out that the package is not required for this repo, so I have removed it.

**Comment by atosystem** [comment]
@afrozas 
Looks like there is no further problem regarding this issue.
I will close this issue, feel free to open it again if the installation still fails.
Thanks!

**Comment by afrozas** [comment]
thanks!
