### ISSUE TITLE
 MIDI data problems and training problems

### ISSUE THREAD

**Issue by dedededefo** [atosystem/ThemeTransformer#5]
Thank you for your excellent work! I have a few questions to ask you. How can I convert my own MIDI data into input suitable for the model? I haven't found a solution in your article. And can I use my own data to train a new model? What should I do?

**Comment by atosystem** [comment]
**Q1** : How can I convert my own MIDI data into suitable input format?
**Ans**: Please go to [Readme](https://github.com/atosystem/ThemeTransformer/tree/main/preprocess#readme) under `./preporcess`

**Q2** : Can I use my own data to train a new model? What should I do?
**Ans**: Yes, you can. You need to follow my data format and annotate the `Themes` in your music by yourself.

**Comment by atosystem** [comment]
@dedededefo I will close this issue now. Feel free to reopen it if you encounter some problem in the future!
