### ISSUE TITLE
Data processing problems

### ISSUE THREAD

**Issue by dedededefo** [atosystem/ThemeTransformer#6]
Hello, thank you very much for your work

I'm trying to use my own data to train your model, but because my MIDI data is single track, I want to know how you get the boundary_ track，melody_ boundary_tracks, theme info tracks，are they added manually？

thank you!

**Comment by atosystem** [comment]
Hi @dedededefo
I use the midi files from POP909, in which each midi file contains 3 tracks: "melody", "bridge", and "piano".
You should run some melody extraction algorithms to attain melody and accompaniment from your single track midi.
For  other tracks (boundary_ track...), please refer to the detail description : [preprocess/readme](https://github.com/atosystem/ThemeTransformer/tree/main/preprocess#readme)

**Comment by atosystem** [comment]
I will close this issue now. You can reopen it if there is any further question.
