### ISSUE TITLE
Data process in prepareDataPkl.py

### ISSUE THREAD

**Issue by ZZDoog** [atosystem/ThemeTransformer#7]
Hi, Ian! Thank you for your excellent job.
I want to process my data from *.midi to *.pkl using your code prepareDataPkl.py lately, and maybe I found some little errors in it.
in line 20 - 25
```
all_mids = sorted(glob.glob(MIDI_FILES))

for _midiFile in all_midis:
    # convert midi files to token representation and save as .pkl file
    output_pkl_fp = midifp.replace(".mid",".pkl")
    remi_seq = myvocab.midi2REMI(midifp,include_bridge=False,bar_first=False,verbose=False)
```
maybe it's `for _midiFile in all_mids:` and `output_pkl_fp = _midifile.replace(".mid",".pkl")`?
And in line 40 and line 45, the definition of  `training_data` is missing.

**Comment by atosystem** [comment]
@ZZDoog  Thanks for pointing out the errors.
I have fixed the bugs and merged update the repo! (#8)
